### ISSUE TITLE
there is no  the file named 'requirements.txt'

### ISSUE THREAD

**Issue by 1earner** [nicolov/gradient_boosting_tensorflow_xgboost#2]
As the commander in read.me, we can not find the file named 'requirements.txt'. Would you like provide the file.
Beside this, as the experiment runs in the blog. Could we use tensorflow GPU support gradient boosting and will the time can reduce?

@nicolov

**Comment by nicolov** [comment]
Uploaded the readme file. I believe that the TF implementation should already use the GPU when possible, but I'm not sure about the speedups you would get.
